### ISSUE TITLE
npm audit high vulnerability from lodash

### ISSUE THREAD

**Issue by Cherviakov** [survivejs/webpack-merge#116]
webpack-merge v4.2.1
nodejs v11.1.0
Linux-Mint-18.4.15
```
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ lodash                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ webpack-merge                                                │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ webpack-merge > lodash                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/782                       │
└───────────────┴──────────────────────────────────────────────────────────────┘

```

**Comment by rishabhsrao** [comment]
(cc @bebraw) I was looking into fixing this. After I forked and cloned the repo, I did the following…

1. Updated `lodash` from `^4.17.5` to `^4.17.15`, like so…
    ```diff
    diff --git a/package.json b/package.json
    index f32e98d..78ab8da 100644
    --- a/package.json
    +++ b/package.json
    @@ -16,7 +16,7 @@
        "lib"
      ],
      "dependencies": {
    -    "lodash": "^4.17.5"
    +    "lodash": "^4.17.15"
      },
      "devDependencies": {
        "babel-cli": "^6.26.0",
    ```
2. Ran `npm install` in order to update `package-lock.json`

But I’m getting a [weird diff in `package-lock.json`](https://i.fluffy.cc/T4wdT4MWcnvqQRPqhXnhLMjlL7wqnnNs.html). It seems to be adding `^` and `~` to all the dependencies. Is this normal?

I also started all over again and used `npm install --save lodash@^4.17.15`. Same issue.

I’m using the following environment…

$ node --version
v12.6.0

$ uname -a
Darwin C02RJ7JGG8WN 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64

**Comment by bebraw** [comment]
> But I’m getting a weird diff in package-lock.json. It seems to be adding ^ and ~ to all the dependencies. Is this normal?

It can be some npm version difference issue. I'll try to look into fixing this over the weekend amongst other issues.

**Comment by rishabhsrao** [comment]
Oh, I see. That might be the issue... By the way, my `npm` version is 6.9.0.

**Comment by badrange** [comment]
Hi! I guess you didn't find the time to fix this over the weekend :-)

**Comment by badrange** [comment]
By the way, I think the changes with ^ and ~ are desirable, and probably caused by improvements in npm

**Comment by bebraw** [comment]
I bumped the minimum for lodash. Sorry for the delay (busy with work atm).

I would love to finish the TS port next.
