### ISSUE TITLE
Confused On Usage

### ISSUE THREAD

**Issue by reintroducing** [survivejs/webpack-merge#117]
Node: v10.3.0
OS: macOS Mojave v10.14.4
webpack-merge: v4.2.1 

I'm working with a config that has the DefinePlugin across two files (a `dev` config and a `common` config). I swear this functionality was working previously for me but it no longer is and I don't know where/when it broke. Basically, whats happening, is that whatever item is on the right takes precedence.

Here is the sample set:
```
console.log(configClientCommon.plugins[0]);
// DefinePlugin { definitions: { 'process.env': { commonVar: 'bar' } } }

console.log(configClientDev.plugins[0]);
// DefinePlugin { definitions: { 'process.env': { NODE_ENV: '"development"', devVar: 'foo' } } }
```

The merge produces this:
```
console.log(webpackMerge(configClientCommon, configClientDev).plugins[0]);
// DefinePlugin { definitions: { 'process.env': { commonVar: 'bar' } } }
```

Reversing produces this:
```
console.log(webpackMerge(configClientDev, configClientCommon).plugins[0]);
// DefinePlugin { definitions: { 'process.env': { NODE_ENV: '"development"', devVar: 'foo' } } }
```

This is all made even more confusing by the following, which is what I'm expecting from my merge:
```
console.log(webpackMerge(
            { DefinePlugin: { definitions: { 'process.env': { commonVar: 'bar' } } } },
            { DefinePlugin: { definitions: { 'process.env': { NODE_ENV: '"development"', devVar: 'foo' } } } }
        ).DefinePlugin);
// { definitions: { 'process.env': { commonVar: 'bar', NODE_ENV: '"development"', devVar: 'foo' } } }
```

What am I missing here? I can't seem to pinpoint what's going on and like I mentioned, this used to work at some point just fine.

**Comment by reintroducing** [comment]
@bebraw I've created a very small test project. Just unzip, npm install, and npm start to see the logs.

[webpack-merge-test.zip](https://github.com/survivejs/webpack-merge/files/3098707/webpack-merge-test.zip)

**Comment by bebraw** [comment]
Hi,

I checked your example zip. **webpack-merge** works in this case exactly as I would expect.

Try adding `console.log(config.plugins[0], config.plugins[1], config.plugins.length);` to your **webpack.config.js**. That will show **two** `DefinePlugin` instances.

It works like this with plugins since it's hard to merge plugin options reliably due to the different ways webpack plugins can be defined. I tried this before and the code became rather problematic.

Is it possible webpack's behavior has changed in case multiple `DefinePlugin`s are used? Can you try against an older version of webpack to verify this?

**Comment by reintroducing** [comment]
@bebraw Gotcha, thanks for the reply. I ended up rewriting my configs and setup to use DefinePlugin in one spot for each environment rather than trying to merge them with webpack-merge. I'll go ahead and close this as a result.
