### ISSUE TITLE
@types/webpack-merge doesn't work with webpack v5

### ISSUE THREAD

**Issue by nzjony** [survivejs/webpack-merge#160]
Not sure if this is the correct place, or if I should create this issue in DefinitelyTyped.

I get the following issue:

```
node_modules/@types/webpack/index.d.ts:32:3 - error TS2305: Module '"../../tapable/tapable"' has no exported member 'Tapable'.

32   Tapable,
     ~~~~~~~

node_modules/@types/webpack/index.d.ts:1062:23 - error TS2707: Generic type 'SyncWaterfallHook<T, AdditionalOptions>' requires between 1 and 2 type arguments.

1062             resolver: SyncWaterfallHook;
```

It is similar to this issue: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/49528#issuecomment-732849209

I can reproduce it here: https://github.com/nzjony/copy-webpack-plugin-types-typescript-test/blob/types-webpack-merge-issue/test.ts

Simply git clone the https://github.com/nzjony/copy-webpack-plugin-types-typescript-test/tree/types-webpack-merge-issue branch and run `npm install && npm run build` to reproduce the error.

**Comment by bebraw** [comment]
Can you open this issue at copy-webpack-plugin repository or DefinitelyTyped? webpack-merge doesn't depend on webpack types directly so we cannot fix the issue here.

**Comment by nzjony** [comment]
@bebraw , sure.

**Comment by bebraw** [comment]
@nzjony Maybe it helps tracing the root cause that starting from webpack 5, you should **not** have `@types/webpack` in your project as now webpack comes with types itself. If you have it in the project at the same time, based on my experience it's going to break things quite severely. Sometimes this occurs when a plugin that hasn't been updated to support webpack 5 yet pulls web`@types/webpack`. That's the first place I would check.

When it comes to **webpack-merge**, I made it so that you can pass the `Configuration` type to it through a generic as doing this decoupled the tool from webpack making it possible to use it across different versions.

**Comment by nzjony** [comment]
@bebraw , my project has no direct dependency to @types/webpack, it is from @types/webpack-merge, i.e.:

```
    "@types/webpack-merge": {
      "version": "4.1.5",
      "resolved": "https://registry.npmjs.org/@types/webpack-merge/-/webpack-merge-4.1.5.tgz",
      "integrity": "sha512-cbDo592ljSHeaVe5Q39JKN6Z4vMhmo4+C3JbksOIg+kjhKQYN2keGN7dvr/i18+dughij98Qrsfn1mU9NgVoCA==",
      "requires": {
        "@types/webpack": "*"
      }
    }
```

**Comment by bebraw** [comment]
@nzjony Maybe that's the problem. **webpack-merge** comes with types and you shouldn't use **@types/webpack-merge** as that's obsolete.
