### ISSUE TITLE
Default to array prepend?

### ISSUE THREAD

**Issue by bebraw** [survivejs/webpack-merge#17]
In Webpack plugin order is significant. This means the first matched plugin wins. Currently **webpack-merge** concatenates arrays in the order it finds them. So if you have `merge(common, prod)`, it will pick up plugins from `common` first and `prod` after that.

This can be problematic if you are trying to apply a plugin like `DedupePlugin` at `prod` as it would have to be before other plugins.

Maybe we should reverse this order? So that instead of appending, we would prepend arrays. That way the last merged array would win and it would become easier to control ordering like this.

Any thoughts? Can you see any problems with this change? It would be a major version bump in any case.

**Comment by insin** [comment]
Given that webpack-merge is specifically targetted at webpack configs, could you change the merge strategy based on the property path being merged to do the thing that's most likely to be right by default?

So for a top-level `plugins` prop, that could be prepending.

Would it also be possible to allow users to override that in case it isn't what they want?

```js
let mySpecialMerge = merge.strategy({plugins: 'append'})
```

**Comment by bebraw** [comment]
> Given that webpack-merge is specifically targetted at webpack configs, could you change the merge strategy based on the property path being merged to do the thing that's most likely to be right by default for a webpack config?
>
> So for a top-level plugins prop, that could be prepending.

Yeah, this is a good idea. I could definitely start that way. Just doing prepend on `plugins` would solve the problem.

Now that I think of it, appending makes sense for properties like `entry`.

> Would it also be possible to allow users to override that in case it isn't what they want?

```javascript
let mySpecialMerge = merge.strategy({plugins: 'append'})
```

looks good to me.

I'll try to get both of these done sometime soon. The basic behavior will remain unchanged apart from that plugin tweak (breaking change -> new major version) but the rest can sit on top of this all.

**Comment by blackrabbit99** [comment]
I guess ```merge.strategy```  could be useful for other case for example for now we can't merge fields with exclude prop. It works as hard concatenation. But on the other hand how will be it complex to analyze   main cases?

**Comment by nrdobie** [comment]
This would solve the problem I am having with entries being prepended. My entry bundle is normally `[ 'babel-polyfill', './index' ]` but on development I use HMR so I need `[ 'webpack/hot/poll?1000', 'babel-polyfill', './index' ]`. In order to get around this I have had to directly update the `entry` property outside of merge to make this work.

**Comment by bebraw** [comment]
@nrdobie That's an excellent point. Is there some particular reason why you can't run webpack-dev-server inline mode? Do you want to give PR a go?

**Comment by bebraw** [comment]
@nrdobie I added `merge.strategy` factory there now. You should be able to do `merge.strategy({ entry: 'prepend' })` to tackle that case. Let me know how it goes.

**Comment by tleunen** [comment]
Is there a way to use the strategy (for the entry for example) with the smart merge as well for the loaders? Or is is best to mix 2 calls of merge?

**Comment by bebraw** [comment]
@tleunen I added `merge.smartStrategy({ entry: 'module.loaders' })` in `0.18.0`. That should give you more control over individual fields. `merge.strategy` supports nested fields now as well.

**Comment by nrdobie** [comment]
@bebraw I am using HMR on a Koa server not a browser application so the `webpack-dev-server` does not work here.

Thanks for this enhancement I've been able to move almost all my code back into the webpack merge and worked perfectly. About the only issue I have left is that in one edge case where I need to completely change the extensions list. I know that this is an extreme edge case but it would be nice if there was a `'replace'` strategy as well.

Here is my extension list:

```
// Production
module.exports.resolve.extensions = [
  '.web.js',
  '.web.jsx',
  '.js',
  '.jsx',
];

// Development
module.exports.resolve.extensions = [
  '.web.dev.js',
  '.web.dev.jsx',
  '.web.js',
  '.web.jsx',
  '.dev.js',
  '.dev.jsx',
  '.js',
  '.jsx',
];
```

Since I have a few instance where I need a `.dev.js` file to fix something in Node for development mode but the browser code to can stay the same I need to make sure my inheritance is correct.

**Comment by bebraw** [comment]
@nrdobie Sounds like a good idea. Can you open a separate issue with a basic spec (input/output) so I get it exactly right? Thanks. 👍
