### ISSUE TITLE
1.1.0 has a breaking change for a single argument

### ISSUE THREAD

**Issue by insin** [survivejs/webpack-merge#46]
If you're merging a list of things using `merge(...list)` or `merge.apply(null, list)` and you aren't checking that you have more than one thing in the list, 1.1.0 is a breaking change.

Caught here: https://travis-ci.org/insin/nwb/jobs/182942656

**Comment by bebraw** [comment]
Thanks. Fixed in `1.1.1`.

The format works with all available functions. Earlier it worked by coincidence (no test) so I missed that.

I wouldn't mind hooking up nwb with Travis so we avoid these kind of situation. Maybe `git clone`, `npm install`, and `npm test` kind of script would be enough? PR would be nice.

Check #45 also. Feedback would be welcome.

**Comment by insin** [comment]
Can you enable GreenKeeper per-dependency? I don't think I could handle the branch-spam it would cause on nwb.

**Comment by bebraw** [comment]
That's a good idea, I'll investigate.

If I do a standalone script, you shouldn't get extra notifications unless you are watching the repo.

Thanks.

**Comment by bebraw** [comment]
@insin I set up GreenKeeper. As I haven't used it before, please go through the setup and let me know if there's anything specific to tweak.
