### ISSUE TITLE
Overriding with an empty array is unexpected behaviour

### ISSUE THREAD

**Issue by sporto** [survivejs/webpack-merge#48]
If I do

```js
var a = {
	plugins: [ pluginA ]
}

var b = {
	plugins: [ ]
}

var c = merge(a, b)
```

`c.plugins` will be empty. I expect merge to concatenates the arrays. So I would expect c.plugins to be `[pluginA]`.

I see that this is in the documentation but it really feels like unexpected behaviour.

**Comment by bebraw** [comment]
Yeah, that's a valid point. It was there earlier because there was to way to replace, but there's now.

I wouldn't mind changing it for 2.0. It's a breaking change, but it would feel like a good move to make.

I'll wait a while to see what other people think. If there are no objections, I'll change it.

Please comment on #45 too. Inline strategies would be a good addition.

**Comment by bebraw** [comment]
I made this change in `2.0.0`. Thanks for the heads up.
