### ISSUE TITLE
Webpack 2 support

### ISSUE THREAD

**Issue by harangue** [survivejs/webpack-merge#51]
My `loaders` (now `rules`) aren't being merged. I'm assuming this tool doesn't support Webpack 2 configs just yet?

**Comment by bebraw** [comment]
Can you provide a minimal example?

**Comment by Tibfib** [comment]
The main change from webpack 1 --> 2 is that module.loaders is now module.rules. And now, instead of either putting `loader` or `loaders` (for an array), it's `loader` or `use` (for an array). Finally, a loader can be an object now instead of just a string. 

Here's a pretty solid example of what that looks like: https://webpack.js.org/configuration/

Here's the formal documentation: https://webpack.js.org/configuration/module/#module-rules


I'm running into issues with webpack-merge when I try to use objects as my loader. (The old module.loaders syntax which webpack-merge supports still works with webpack2).

For the following code: 
```javascript
module: {
	loaders: [
		{
			test: /\.css$/,
			loaders: [
				'style-loader',
				{
					loader: 'css-loader',
					query:  {
						sourceMap: true
					}
				}
			]
		}
	]
}
```
I get this error.
```
/.../node_modules/webpack-merge/lib/index.js:16
      return loader.match(loaderNameRe)[0] !== l.match(loaderNameRe)[0];
                    ^

TypeError: loader.match is not a function
```

Webpack 2 support here would be awesome!

**Comment by bebraw** [comment]
Can you give me a complete example?

```javascript
const merge = require('webpack-merge')

a = {module: {
	loaders: [
		{
			test: /\.css$/,
			loaders: [
				'style-loader',
				{
					loader: 'css-loader',
					query:  {
						sourceMap: true
					}
				}
			]
		}
	]
}}

console.log(merge(a, {}));
```

doesn't error for me.

**Comment by Tibfib** [comment]
Shoot, I realized webpack-blocks is using webpack-merge v0.14.1... This works properly on versions > 1.1.2.

Thanks! Sorry for the false alarm (and for hijacking this thread!)

**Comment by harangue** [comment]
There was other stuff afoot for me as well. Closing.
