### ISSUE TITLE
Have smartStrategy merge loaders based on match of module.rules.test

### ISSUE THREAD

**Issue by kirbyjs** [survivejs/webpack-merge#91]
Hello! Is there any way to use `smartStrategy` for merging two loaders together even if other properties besides test don't match? 

common: 
```js
 module: {
      rules: [{
            exclude: /some regex/,
            use: ['common-loader'],
            test: /\.js$/
    }]
}
```
prod:
```js
 module: {
      rules: [{
            exclude: /different regex/,
            use: ['another-common-loader'],
            test: /\.js$/
    }]
}
```
expected result: 
```js
 module: {
      rules: [{
            exclude: /different regex/,
            use: ['common-loader', 'another-common-loader'],
            test: /\.js$/
    }]
}
```
I noticed [here](https://github.com/survivejs/webpack-merge/blob/master/src/join-arrays-smart.js#L8) that you have multiple checks before you start merging loaders. Is there any way that consumers could pass in configurations to allow it to be less strict before merging? So in this case above, I don't care that the `exclude`'s don't match, I just want to smash my js loaders together.

**Comment by kirby15** [comment]
I noticed #90 in a way relates to my issue. I would like to ask some questions to your responses (I do get in his case it makes sense to use `.babelrc` though). So, in what case would a consumer use 3+ objects that are trying to merge the same `test`?  And if there were was a case then wouldn't the expected behavior be like how the spread operator works: 
```js 
{
   ...obj1
   ...obj2
   ...obj3
}
```
Whereas the difference in this case would be that the array of loaders are getting joined? 

Or to hit on another point, when ever would there be a case when I want two loaders that have the same `test`?

ie
```js
 module: {
      rules: [
        {
            exclude: /some regex/,
            use: ['common-loader'],
            test: /\.js$/
        },
        {
            exclude: /different regex/,
            use: ['another-common-loader'],
            test: /\.js$/
        }
    ]
}
```

**Comment by bebraw** [comment]
I don't think the case you describe is supported the way you want. It's that `exclude` that's the problem since there's no one right way to handle that case. If I remember right, now it returns different rules if `exclude` is defined.

This might be one more reason to deprecate `merge.smart`. Too many issues like this.

**Comment by kirby15** [comment]
> If I remember right, now it returns different rules if exclude is defined

Yes that is what the code is doing right now [here](https://github.com/survivejs/webpack-merge/blob/master/src/join-arrays-smart.js#L11), from what I can tell. 

I guess, if nothing goes my way, I would be okay with defining my own `customizeArray` with `merge`. I still would really like `smart`'s behavior to not care about anything other than test, and behave as I've described above, by just replacing any other property that the consumer has defined with the new rule's property, _unless_ the property is an array. 

Also, imo, I would hate to see `smart` go, this would require a lot of people that are using `smart` to write their own `customizeArray`/`customizeObject` with the `merge` function.

**Comment by bebraw** [comment]
> Also, imo, I would hate to see smart go, this would require a lot of people that are using smart to write their own customizeArray/customizeObject with the merge function.

I guess the point would be that we would provide current "smartness" through that and allow some form of composition so you could pick some default behavior while adding special cases to it. Then the package itself has to do a little less.

**Comment by kirby15** [comment]
I would be okay with what you've described above, and personally think it's a pretty good option. I assume that would take some time to add though? I guess for now I'll just use `customizeArray`.

**Comment by bebraw** [comment]
> I would be okay with what you've described above, and personally think it's a pretty good option. I assume that would take some time to add though? I guess for now I'll just use customizeArray.

It would take some re-design, yup. I don't have a lot of development time at the moment (running my own business) but it might happen some day if someone decides to do it. 😄

**Comment by bebraw** [comment]
I'll drop support for `merge.smart` and `merge.smartStrategy` in the next major version as it's tricky to support due to different webpack versions and overall complexity.

Can you rewrite the configuration in terms of regular `merge` or `mergeStrategy`? I use solely `merge` for all of my personal work as it's predictable.
